services:
  clashperk_bot:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/clashperk-bot:latest
    restart: always
    container_name: clashperk_bot
    # build:
    #   context: .
    env_file:
      - .env
    mem_limit: 8gb
    ports:
      - '8070:8080'
    # healthcheck:
    #   test: wget -qO - localhost:8080 || exit 1
    #   interval: 60s
    #   timeout: 30s
    #   retries: 1
    #   start_period: 60s
    networks:
      - default_net

networks:
  default_net:
    external: true
    name: default_net
